DROP DATABASE IF EXISTS projeto_php;

CREATE DATABASE IF NOT EXISTS projeto_php;

USE projeto_php;

CREATE TABLE IF NOT EXISTS users
(
    id          INT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username    VARCHAR(50),
    email       VARCHAR(50),
    birth_date  DATETIME  NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

